/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memory;


import java.awt.*;
import javax.swing.*;

public class VisuPersonnagesDlg extends javax.swing.JDialog {

    private Joueur j; //joueur dont les cartes sont à afficher
 
   public VisuPersonnagesDlg(java.awt.Frame parent, boolean modal, Joueur j) {
        super(parent, modal);
        initComponents();
        this.j = j;
        initPanneau();
        Joueur.setText("Cartes du joueur : "+j.getPseudo());
        Score.setText("Score : "+j.getScore());
    }
   
    
    public  void initPanneau()
    {   
        LesPersonnages lc = j.getPaquet();
        int nbi= lc.getTaille();
        // taille de la grille nxn
        int n= (int) Math.floor(Math.sqrt(nbi))+1; 
        Panneau.setLayout(new java.awt.GridLayout(n, n));
        for (int i =0; i<nbi; i++)
        { 
            JButton bt= new JButton();
            Panneau.add(bt);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panneau = new javax.swing.JPanel();
        Joueur = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Score = new javax.swing.JLabel();
        Afficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);
        getContentPane().add(Joueur, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));
        jPanel1.add(Score);

        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });
        jPanel1.add(Afficher);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
        // TODO add your handling code here:
        
         for (int i=0; i<this.j.getPaquet().getTaille(); i++)
    { 
        JButton jb= (JButton) Panneau.getComponent(i);
        Personnage p= this.j.getPaquet().getPerso(i);
        Image img = p.getPhoto().getScaledInstance(jb.getWidth(), jb.getHeight(),Image.SCALE_DEFAULT);
        jb.setIcon(new ImageIcon(img));
    }
    }//GEN-LAST:event_AfficherActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JLabel Joueur;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel Score;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
